import Link from "next/link"
import "./globals.css"

export const metadata = {
  title: {
    default:" salah portfolio",
    template:"%s | salah portfolio"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       


      <body>   
      <nav className="bg-blue-500 p-4 shadow-md">
      <div className="max-w-7xl mx-auto flex items-center justify-between">
        <div className="text-white text-lg font-bold">MyApp</div>
        <ul className="flex space-x-6">
          <li>
            <Link href="/" className="text-white hover:text-gray-300">Home</Link>
          </li>
          <li>
            <Link href="/about" className="text-white hover:text-gray-300">About</Link>
          </li>
          <li>
            <Link href="/contact" className="text-white hover:text-gray-300">Contact</Link>
          </li>
        </ul>
      </div>
    </nav>
        
        <div >
        {children}
        </div>





      <footer className="bg-gray-800 text-white py-6">
      <div className="max-w-7xl mx-auto text-center">
        <p>&copy; 2025 MyApp. All rights reserved.</p>
        <ul className="mt-4 flex justify-center space-x-6">
          <li><Link href="/privacy" className="hover:text-gray-400">Privacy</Link></li>
          <li><Link href="/terms" className="hover:text-gray-400">Terms</Link></li>
          <li><Link href="/contact" className="hover:text-gray-400">Contact</Link></li>
        </ul>
      </div>
    </footer>
      </body>


     
    </html>
  )
}
